export const AUTH_LOGIN = `AUTH_LOGIN`;
export const AUTH_LOGOUT = `AUTH_LOGOUT`;
export const OPEN_CHANGE_PASSWORD_MODAL = `OPEN_CHANGE_PASSWORD_MODAL`;
export const CLOSE_CHANGE_PASSWORD_MODAL = `CLOSE_CHANGE_PASSWORD_MODAL`;

export const SWITCH_AUTH_MODE = `SWITCH_AUTH_MODE`;

export const CHANGE_PAGE_TITLE = `CHANGE_PAGE_TITLE`;

export const ADD_FILTER_FROM_CHECKBOXES = `ADD_FILTER_FROM_CHECKBOXES`;
export const ADD_FILTER_FROM_INPUT = `ADD_FILTER_FROM_INPUT`;

export const REMOVE_FILTER = `REMOVE_FILTER`;

export const CHANGE_TOGGLE_POSITION = `CHANGE_TOGGLE_POSITION`;
export const SAVE_CHANGES_POLICY = `SAVE_CHANGES_POLICY`;
export const CANCEL_CHANGES_POLICY = `CANCEL_CHANGES_POLICY`;

export const SET_RESULT_FROM_SERVER = `SET_RESULT_FROM_SERVER`;
export const RESET_STATE = `RESET_STATE`;
