export const AUTH_LOGIN = `AUTH_LOGIN`;
export const AUTH_LOGOUT = `AUTH_LOGOUT`;

export const SWITCH_AUTH_MODE = `SWITCH_AUTH_MODE`;

export const CHANGE_PAGE_TITLE = `CHANGE_PAGE_TITLE`;

export const ADD_FILTER_FROM_CHECKBOXES = `ADD_FILTER_FROM_CHECKBOXES`;
export const ADD_FILTER_FROM_INPUT = `ADD_FILTER_FROM_INPUT`;

export const REMOVE_FILTER = `REMOVE_FILTER`;
