export const AUTH_LOGIN = `AUTH_LOGIN`;
export const AUTH_LOGOUT = `AUTH_LOGOUT`;

export const SWITCH_AUTH_MODE = `SWITCH_AUTH_MODE`;

export const CHANGE_PAGE_TITLE = `CHANGE_PAGE_TITLE`;

export const ADD_FILTER_FROM_CHECKBOXES = `ADD_FILTER_FROM_CHECKBOXES`;
export const ADD_FILTER_FROM_INPUT = `ADD_FILTER_FROM_INPUT`;

export const REMOVE_FILTER = `REMOVE_FILTER`;

export const CHANGE_TOGGLE_POSITION = `CHANGE_TOGGLE_POSITION`;
export const SAVE_CHANGES_POLISY = `SAVE_CHANGES_POLISY`;
export const CANCEL_CHANGES_POLISY = `CANCEL_CHANGES_POLISY`;
