apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: icap-management-ui
          image: {{ .Values.imagestore.icapmanagementui.repository }}:{{ .Values.imagestore.icapmanagementui.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TRANSACTION_EVENT_API_URL
              value: {{ .Values.config.transactionEventApiUrl }}
            - name: POLICY_MANAGEMENT_API_URL
              value: {{ .Values.config.policyManagementApiUrl }}
            - name: TLS_CERT
              value: {{ .Values.secrets.tlsCert }}
            - name: TLS_KEY
              value: {{ .Values.secrets.tlsKey }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
