export const CHANGE_PAGE_TITLE = `CHANGE_PAGE_TITLE`;

export const TOGGLE_NAV_EXPANDED = `TOGGLE_NAV_EXPANDED`;

export const RESET_STATE = `RESET_STATE`;

// Auth
export const AUTH_LOGIN = `AUTH_LOGIN`;
export const AUTH_LOGOUT = `AUTH_LOGOUT`;
export const OPEN_CHANGE_PASSWORD_MODAL = `OPEN_CHANGE_PASSWORD_MODAL`;
export const CLOSE_CHANGE_PASSWORD_MODAL = `CLOSE_CHANGE_PASSWORD_MODAL`;
export const SWITCH_AUTH_MODE = `SWITCH_AUTH_MODE`;

// Request History
export const ADD_FILTER_FROM_CHECKBOXES = `ADD_FILTER_FROM_CHECKBOXES`;
export const ADD_FILTER_FROM_INPUT = `ADD_FILTER_FROM_INPUT`;
export const REMOVE_FILTER = `REMOVE_FILTER`;
export const UPDATE_REQUEST_HISTORY_TIME_FILTER = `UPDATE_REQUEST_HISTORY_TIME_FILTER`;

// Policy
export const SET_POLICY_ERROR = `SET_POLICY_ERROR`;
export const SET_STATUS = `SET_STATUS`;
export const SET_IS_POLICY_CHANGED = `SET_IS_POLICY_CHANGED`;
export const SET_CURRENT_POLICY = `SET_CURRENT_POLICY`;
export const SET_DRAFT_POLICY = `SET_DRAFT_POLICY`;
export const SET_POLICY_HISTORY = `SET_POLICY_HISTORY`;
export const SET_NEW_DRAFT_POLICY = `SET_NEW_DRAFT_POLICY`;
export const CANCEL_DRAFT_CHANGES = `CANCEL_DRAFT_CHANGES`;

